### PR TITLE
AOT compatibility

### PR DESCRIPTION
**Pull request by sledorze**
Lenticular fails to compile with strict typescript options.
Generally this is *not* an issue as one can use 'skipLibCheck', however, in an AOT context, 'skipLibCheck' will not have the desired effect.
Hence this PR.

### CODE REVIEW

**Comment by tomasdeml** [comment]
First off, thank you for the PR! I should have checked compatibility with strict TSC options sooner. 

Could you please provide more context for the AOT compatibility? I guess you refer to Angular's AOT compiler?

The PR looks mostly fine, however I need to think about the `IPath` interface - the dummy fields look a little bit strange there. Also, I need to update build tasks for gulp to the latest version of TypeScript. Hang on...

**Comment by sledorze** [comment]
@tomasdeml Yes, I'm referring to the Angular AOT compiler (lenticular plays well in a ngrx context).
I acknowledge the dummy fields are strange (and ugly, no desirable, etc..), the reason is that the compiler was complaining as the type parameters were not used..

**Comment by sledorze** [comment]
@tomasdeml closing it due to inactivity

**Comment by tomasdeml** [comment]
The issue should be fixed in version 5.0.0.

**Pull request closed without merging**
